name: Build 📱 iOS & 🤖 Android

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Версия релиза'
        required: true
        default: '1.0.0'

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
      - run: flutter pub get
      - run: pod repo update
        working-directory: ios
      - run: flutter build ios --release --no-codesign
      - run: mkdir Payload
        working-directory: build/ios/iphoneos
      - run: mv Runner.app Payload
        working-directory: build/ios/iphoneos
      - name: Zip iOS .ipa
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos
      - name: Upload iOS .ipa as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/FlutterIpaExport.ipa
          
  build-android:
    name: 🤖 Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
      - run: flutter build apk --release
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  create-release:
    name: 📦 Create GitHub Release
    needs: [build-ios, build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          files: |
            artifacts/ios-ipa/FlutterIpaExport.ipa
            artifacts/android-apk/app-release.apk
          body: "Release v${{ github.event.inputs.version }} - GTD Task"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
