name: Build 📱 iOS & 🤖 Android

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Update CocoaPods repos
        run: pod repo update
        working-directory: ios

      - name: Build iOS release (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Prepare Payload folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move .app into Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip into .ipa
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload iOS .ipa to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Release v1.0 – iOS IPA"

  build-android:
    name: 🤖 Android Build
    runs-on: ubuntu-latest
    needs: build-ios
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses

      - name: Cache Gradle and Pub
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Build Android release APK
        run: flutter build apk --release

      - name: Upload Android .apk to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          tag: v1.0
          overwrite: true
          body: "Release v1.0 – Android APK"
